Fix a break caused by pages without images
Wikipedia pages without images cause `image_metadata` to be `nil`. Thus, calling `.image_urls` or `.image_descriptionurls` ends in `NoMethodError: undefined method `map' for nil:NilClass`. This commit just modifies those methods so that they return `nil` if `image_metadata` is `nil`.